services:
  - type: web
    name: sptinder-api
    region: ohio
    plan: free
    env: node
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: REDIRECT_URI
        value: https://sptinder-api.onrender.com/auth/callback

  - type: static
    name: sptinder-web
    region: ohio
    plan: free
    rootDir: apps/web
    buildCommand: npm install && npm run build
    publishPath: dist