apiVersion: v1
kind: Service
metadata:
  name: {{ include "sptinder.fullname" . }}-realtime
  labels:
    {{- include "sptinder.labels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3001
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "sptinder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: realtime