apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sptinder.fullname" . }}-secrets
  labels:
    {{- include "sptinder.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.database.password | b64enc }}
  redis-url: {{ .Values.redis.password | b64enc }}
  spotify-client-id: {{ .Values.spotify.clientId | b64enc }}
  spotify-client-secret: {{ .Values.spotify.clientSecret | b64enc }}
  jwt-secret: {{ .Values.jwt.secret | b64enc }}